name: asciichart Publish

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

env:
  ELIXIR_VERSION: "1.15"
  OTP_VERSION: "24.3"
  HEX_API_KEY: ${{ secrets.HEX_API_KEY }}

jobs:
  elixir:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ env.ELIXIR_VERSION }}
          otp-version: ${{ env.OTP_VERSION }}

      - name: Build and publish
        run: |
          mix deps.get
          mix deps.compile
          mix hex.publish --yes

  release:
    runs-on: ubuntu-latest
    needs:
      - elixir
    steps:
      - name: Release
        uses: softprops/action-gh-release@v1
