name: asciichart Release

on:
  workflow_dispatch:
    inputs:
      next_version:
        description: 'Next release version'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/master'

    steps:
      - uses: sndnv/action-release-next@v1
        with:
          next_version: ${{ inputs.next_version }}
          target_branch: master
          release_key: ${{secrets.RELEASE_KEY}}
          version_files_json: |
            {
              "mix.exs": "\\s*version: \"(\\d+\\.\\d+\\.\\d+.*)\",$"
            }
